[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
reward_pool_main = "3pCyA3bZvZABQykEPfCtfd8U6fgV7pxajBi1ZVGZjQqu"

[programs.localnet]
reward_pool_main = "EXvNxLKMjDzMPUDhA4pqRVXQM8VU57tFSecUEq79QJ9L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
